#!/bin/bash


# Control Node
# At least one and only one node (for now).
CONTROL_NODE_PUBLIC_IP='147.75.77.139'
CONTROL_NODE_PRIVATE_IP='10.100.143.137'

# Network Node(s)
# At least one node. Could be more (separated by commas).
NETWORK_NODES_PRIVATE_IP='10.100.143.137'
NETWORK_NODES_NEUTRON_EXT_IF='veth_2_b'

# Compute Node(s)
# At least one node. Could be more (separated by commas).
COMPUTE_NODES_PRIVATE_IP='10.100.143.131,10.100.143.137'

# Storage Node(s)
# At least one node. Could be more (separated by commas).
STORAGE_NODES_PRIVATE_IP='10.100.143.137,10.100.143.131'
STORAGE_NODES_CEPH_OSD_DATA_DIR='/var/lib/stackube/ceph/ceph_osd,/var/lib/stackube/ceph/ceph_osd'


# NEUTRON_PUBLIC_SUBNET='subnet-range;gateway;allocation-pool'
NEUTRON_PUBLIC_SUBNET='147.75.192.224/29;147.75.192.225;start=147.75.192.226,end=147.75.192.228'


#CEPH_FSID=

#RABBITMQ_PWD=

#MYSQL_ROOT_PWD=
#MYSQL_KEYSTONE_PWD=
#MYSQL_NEUTRON_PWD=
#MYSQL_CINDER_PWD=

#KEYSTONE_ADMIN_PWD=
#KEYSTONE_NEUTRON_PWD=
#KEYSTONE_CINDER_PWD=


